# Builds the JC'S JOURNALS page (jcsjournals.com): the library page rebranded
# per JC's 7/19 direction: JC's Journals wordmark + social icons in the header,
# brand-colored social cards section, free course/paid tiers PARKED as "coming
# soon" (TD101 links de-linked, not deleted), My Journey removed, full legal
# docs (Terms 2/25 + Medical/Privacy 3/31) in the footer modal, no Contact.
#
# Input : site-masters\mdhs-library-page.html  (generated by build-library-page.ps1, run that first)
# Parts : repo\src\jcj-parts\*                 (header, socials, footer, mnav, legal docs, extra CSS)
# Output: site-masters\jcj-page.html           (full page master; split-jcj.ps1 makes the CDN files)
#
# Every replacement is verified (exact expected match count): a drifted master
# fails the build loudly instead of shipping a half-transformed page.
$ErrorActionPreference = 'Stop'
$repo    = "C:\Users\taino\jcsjournals-site"
# urls.ps1 is THE single place page URLs are defined. The library master this
# page is generated FROM already has them substituted in, so the patterns below
# must be built from the same variables or a URL change silently breaks them.
. "$repo\tools\urls.ps1"
$masters = "D:\00. MUCUS-FREE LIFE\01. Operations\02. Working Procedures\Claude SOPs\00. JC Brand\JC Website\site-masters"
$parts   = "$repo\src\jcj-parts"
$utf8    = New-Object System.Text.UTF8Encoding($false)

$h = [IO.File]::ReadAllText("$masters\mdhs-library-page.html", [Text.Encoding]::UTF8)
function Part([string]$name) { [IO.File]::ReadAllText("$parts\$name", [Text.Encoding]::UTF8) }

function RepRx([string]$label, [string]$pattern, [string]$replacement, [int]$expect) {
  $m = [regex]::Matches($script:h, $pattern)
  if ($m.Count -ne $expect) { throw "build-jcj: $label matched $($m.Count), expected $expect" }
  $script:h = [regex]::Replace($script:h, $pattern, { param($mm) $replacement })
  Write-Output "  $label : $expect ok"
}

# title ([char]0xB7 = the middle dot; this file is read as ANSI by PS 5.1)
$oldTitle = '<title>Free Education ' + [char]0xB7 + ' The Mucusless Diet Healing System</title>'
RepRx 'title' ([regex]::Escape($oldTitle)) '<title>JC&rsquo;s Journals &middot; Mucus-Free Made Simple</title>' 1

# header + dropdown-JS removal are now INHERITED from the library master
# (build-library-page.ps1 does both, so all three sites share one header).
# Assert rather than repeat, so a drift upstream fails here loudly.
if ([regex]::Matches($h, [regex]::Escape('<a class="wordmark"')).Count -ne 1) { throw "build-jcj: inherited wordmark header missing" }
if ($h -match "var freeBtn=document\.getElementById\('freeBtn'\)") { throw "build-jcj: orphaned dropdown JS survived upstream" }
Write-Output "  header inherited : ok"

# hero PARKED (v9, JC 7/20): the whole "Mucus-Free Made Simple" hero is gone;
# the webinar banner is now the top of the page. The v8 hero (JC's intro line +
# trimmed lede) is saved verbatim in src\jcj-parts\parked-hero.html with its
# restore recipe; the v4-v6 hero transform steps live in git history
# (438db1b..9b7af9d) if the transform route is ever preferred.
RepRx 'hero-remove' '(?s)<div class="hero">.*?</div>\s*(?=<section id="library">)' '' 1

# ORDER (v13, JC 7/24): video FIRST -> the CTA (cta-block, moved up to sit
# right under the "What Is the MDHS?" video) -> library -> socials
# v6 dividers DELETED in v7 (JC 7/20, Carrd's own hr styling threw them off-center)
# v12 (JC 7/23): webinar banner was the REPLAY promo.
# v13 (JC 7/24): webinar banner REMOVED entirely (replay run over), and the CTA
# was pulled up here from the bottom-of-page insert. webinar-banner.html stays on
# disk (its LIVE copy is in git history) for reuse at the next event.
# v14 (JC 2026-08-25): cta-block is now the TD101 waitlist CTA, not the
# Calendly "Speak To A Real Person" box. Its __SIGNUP__ token is the ONLY
# place this file's URL is resolved, straight from urls.ps1's $SignupUrl.
RepRx 'video+cta-insert' ([regex]::Escape('<section id="library">')) ((Part 'video.html') + "`n" + (Part 'cta-block.html') + "`n" + '<section id="library">') 1
RepRx 'cta-signup-url' ([regex]::Escape('href="__SIGNUP__"')) ('href="' + $SignupUrl + '"') 1
if ($h -match 'calendly\.com') { throw "build-jcj: a calendly link resurfaced in cta-block" }
RepRx 'library-heading' ([regex]::Escape('<!-- READ-IN-ORDER PATH -->')) ('<div class="sect-head">' + "`n" + '        <p class="kicker k-free">Free &middot; No Email Signup Required</p>' + "`n" + '        <h2>The Free Library</h2>' + "`n" + '      </div>' + "`n" + '      <!-- READ-IN-ORDER PATH -->') 1

# TD101 course parked -> LIVE (2026-08-21). The library upstream now ships 14
# LIVE tdlink anchors (JC overruled the 2026-08-11 "parked" downgrade), so this
# page inherits live anchors, not dead spans. Assert the new reality, do not
# repeat the old one. This inherited body is discarded a few steps down by the
# "library -> pointer" replace, so nothing here reaches the final page, but the
# assert must still match or the build throws.
if ([regex]::Matches($h, '<a class="tdlink[^"]*" href=').Count -ne 14) { throw "build-jcj: expected 14 inherited live tdlinks" }
if ([regex]::Matches($h, '<span class="tdlink">').Count -ne 0) { throw "build-jcj: a dead tdlink span survived upstream" }
Write-Output "  parked course inherited : 14 ok"
RepRx 'course-note-chip' ([regex]::Escape('Transition Diet 101</a> teaches.</span></div>')) ('Transition Diet 101</a> teaches. <span class="soonchip">Coming Soon</span></span></div>') 1
$fr = [regex]::Matches($h, [regex]::Escape('Transition Diet 101</a> course.')).Count
if ($fr -lt 1) { throw "build-jcj: framing-chip found none" }
$h = $h.Replace('Transition Diet 101</a> course.', 'Transition Diet 101</a> course. <span class="soonchip">Coming Soon</span>')
Write-Output "  framing-chip : $fr ok"

# socials after the library (v13, JC 7/24: the CTA block moved up under the video,
# so only socials is inserted here now)
RepRx 'socials-insert' ([regex]::Escape('<dialog id="legalModal">')) ((Part 'socials.html') + "`n" + '<dialog id="legalModal">') 1

# footer (Terms/Medical/Privacy only, no Contact) + mobile pill Library/Socials
RepRx 'footer' '(?s)<footer>.*?</footer>' (Part 'new-footer.html') 1
# THE DOCK BAR is INHERITED from the library master (build-library-page.ps1
# injects it there, and this page is generated from that master, so the layering
# gives it to us for free). ⛔ It carries no Contact/Calendly item (removed
# 2026-08-25, JC): there is no way to book a call from any site in the family.
$dockCount = [regex]::Matches($h, '<nav class="dockbar"').Count
if ($dockCount -ne 1) { throw "build-jcj: expected exactly 1 inherited dock, found $dockCount" }
if ($h -match 'dock-contact|calendly\.com') { throw "build-jcj: a contact/calendly reference resurfaced" }

# full legal docs into the modal
RepRx 'legal-object' '(?m)^const LEGAL=\{.*$' (Part 'legal.js') 1

# JS funnel end-buttons: paid -> socials
RepRx 'endbtn-text' ([regex]::Escape("go.innerHTML='Explore the paid services ")) "go.innerHTML='See my social media " 1
$paidUrl = $LandingUrl + '#paid'
$pc = [regex]::Matches($h, [regex]::Escape($paidUrl)).Count
if ($pc -ne 2) { throw "build-jcj: expected 2 JS paid URLs, found $pc" }
$h = $h.Replace($paidUrl, '#socials')
Write-Output "  js-paid-urls : 2 ok"

# Carrd eats hash navigation -> in-page # links scroll via JS instead (v5)
# ⛔ cta-inline.js DELETED 2026-08-25 (JC): it injected a per-topic Calendly
# "Free 15-Min Call" strip, a second Calendly access point besides cta-block.
$rxScript = New-Object System.Text.RegularExpressions.Regex('(?m)^</script>$')
if (-not $rxScript.IsMatch($h)) { throw "build-jcj: closing script marker not found" }
$jsIns = (Part 'anchor-fix.js').TrimEnd() + "`n</script>"
$h = $rxScript.Replace($h, [System.Text.RegularExpressions.MatchEvaluator]{ param($mm) $jsIns }, 1)
Write-Output "  anchor-fix js merged : ok"

# rebrand CSS merged INTO the main style block (split-jcj expects one block)
$rxStyle = New-Object System.Text.RegularExpressions.Regex('(?m)^</style>$')
if (-not $rxStyle.IsMatch($h)) { throw "build-jcj: closing style marker not found" }
$cssIns = (Part 'jcj-extra.css').TrimEnd() + "`n</style>"
$h = $rxStyle.Replace($h, [System.Text.RegularExpressions.MatchEvaluator]{ param($mm) $cssIns }, 1)
Write-Output "  extra-css merged : ok"

# ---- THE LIBRARY MOVES OUT (JC 2026-08-10) ----
# The hub keeps the "Free, No Email Signup Required / The Free Library" heading
# (his copy, untouched) and now POINTS at the library's own site instead of
# carrying all six topics inline. The hub's job is the video, the human, and
# the routing; the library is its own page in the same design.
$libSectionRx = '(?s)<section id="library">.*?</section>\s*(?=<!-- funnel -->)'
$m = [regex]::Matches($h, $libSectionRx)
if ($m.Count -ne 1) { throw "build-jcj: library section matched $($m.Count), expected 1" }
# ONE box, two free doors, recipe book FIRST with a hairline divider between
# them (JC 2026-08-11). The library is labelled "Learn The Basics" here, not
# "The Free Library", because that is what it does for someone landing cold.
$libPointer = @"
<section id="library">
      <div class="sect-head">
        <p class="kicker k-free">Free &middot; No Email Signup Required</p>
        <h2>Start Here, Free</h2>
      </div>
      <div class="startbox">
        <div class="startrow">
          <div class="starttext">
            <h3>24 Free Recipes</h3>
            <p>The <a class="tdlink" href="$SignupUrl">TD 101</a> Recipe Book. Every recipe with the context behind it: which menu plan it belongs to, when to eat it, and how it fits into a full day.</p>
          </div>
          <a class="btn" href="$RecipesUrl">Open The Recipe Book</a>
        </div>
        <div class="startdiv" aria-hidden="true"></div>
        <div class="startrow">
          <div class="starttext">
            <h3>Learn The Basics</h3>
            <p>The free educational library. Six topics that take you from what the Mucusless Diet Healing System is, to how to actually eat a meal.</p>
          </div>
          <a class="btn" href="$LibraryUrl">Open The Library</a>
        </div>
        <div class="startdiv" aria-hidden="true"></div>
        <div class="startrow">
          <div class="starttext">
            <h3>Start Your Practice</h3>
            <p>In this 100% free course you will learn how to apply the Mucusless Diet Healing System to your unique body and your unique lifestyle. This course covers every single thing I wish I knew when I first started my practice over five years ago.</p>
          </div>
          <a class="btn" href="$SignupUrl">Learn more</a>
        </div>
      </div>
    </section>

"@
$h = [regex]::Replace($h, $libSectionRx, { param($mm) $libPointer })
Write-Output ("  library -> pointer : ok (" + [math]::Round($m[0].Value.Length/1kb) + " KB of inline topics removed)")

# guards
if ([regex]::Matches($h, 'td101landing|td101library').Count -ne 0) { throw "build-jcj: residual dead td101 subdomain refs" }
if ([regex]::Matches($h, 'class="acc cat"').Count -ne 0) { throw "build-jcj: library accordions survived the pointer swap" }
if ([regex]::Matches($h, [regex]::Escape($LibraryUrl)).Count -lt 1) { throw "build-jcj: no link to the library" }
if ([regex]::Matches($h, [regex]::Escape($SignupUrl)).Count -lt 2) { throw "build-jcj: the hub must carry at least 2 paths to the course (the third card + the inline mention)" }
if ([regex]::Matches($h, '<div class="startrow">').Count -ne 3) { throw "build-jcj: expected 3 Start Here cards" }
Write-Output "  hub course paths : ok"
$dockCount = [regex]::Matches($h, '<nav class="dockbar"').Count
if ($dockCount -ne 1) { throw "build-jcj: expected exactly 1 dock in the output, found $dockCount" }
if ([regex]::Matches($h, '(?s)<nav class="mnav"').Count -ne 0) { throw "build-jcj: the old mobile pill resurfaced" }
if ([regex]::Matches($h, 'My Journey').Count -ne 0)   { throw "build-jcj: My Journey resurfaced" }

[IO.File]::WriteAllText("$masters\jcj-page.html", $h, $utf8)
Write-Output ("jcj master written: " + [math]::Round((Get-Item "$masters\jcj-page.html").Length / 1kb) + " KB")
