# Builds the JC'S JOURNALS page (jcsjournals.com): the library page rebranded
# per JC's 7/19 direction: JC's Journals wordmark + social icons in the header,
# brand-colored social cards section, free course/paid tiers PARKED as "coming
# soon" (TD101 links de-linked, not deleted), My Journey removed, full legal
# docs (Terms 2/25 + Medical/Privacy 3/31) in the footer modal, no Contact.
#
# Input : site-masters\mdhs-library-page.html  (generated by build-library-page.ps1, run that first)
# Parts : repo\src\jcj-parts\*                 (header, socials, footer, mnav, legal docs, extra CSS)
# Output: site-masters\jcj-page.html           (full page master; split-jcj.ps1 makes the CDN files)
#
# Every replacement is verified (exact expected match count): a drifted master
# fails the build loudly instead of shipping a half-transformed page.
$ErrorActionPreference = 'Stop'
$repo    = "C:\Users\taino\jcsjournals-site"
# urls.ps1 is THE single place page URLs are defined. The library master this
# page is generated FROM already has them substituted in, so the patterns below
# must be built from the same variables or a URL change silently breaks them.
. "$repo\tools\urls.ps1"
$masters = "D:\00. MUCUS-FREE LIFE\01. Operations\02. Working Procedures\Claude SOPs\00. JC Brand\JC Website\site-masters"
$parts   = "$repo\src\jcj-parts"
$utf8    = New-Object System.Text.UTF8Encoding($false)

$h = [IO.File]::ReadAllText("$masters\mdhs-library-page.html", [Text.Encoding]::UTF8)
function Part([string]$name) { [IO.File]::ReadAllText("$parts\$name", [Text.Encoding]::UTF8) }

function RepRx([string]$label, [string]$pattern, [string]$replacement, [int]$expect) {
  $m = [regex]::Matches($script:h, $pattern)
  if ($m.Count -ne $expect) { throw "build-jcj: $label matched $($m.Count), expected $expect" }
  $script:h = [regex]::Replace($script:h, $pattern, { param($mm) $replacement })
  Write-Output "  $label : $expect ok"
}

# title ([char]0xB7 = the middle dot; this file is read as ANSI by PS 5.1)
$oldTitle = '<title>Free Education ' + [char]0xB7 + ' The Mucusless Diet Healing System</title>'
RepRx 'title' ([regex]::Escape($oldTitle)) '<title>JC&rsquo;s Journals &middot; Mucus-Free Made Simple</title>' 1

# header + dropdown-JS removal are now INHERITED from the library master
# (build-library-page.ps1 does both, so all three sites share one header).
# Assert rather than repeat, so a drift upstream fails here loudly.
if ([regex]::Matches($h, [regex]::Escape('<a class="wordmark"')).Count -ne 1) { throw "build-jcj: inherited wordmark header missing" }
if ($h -match "var freeBtn=document\.getElementById\('freeBtn'\)") { throw "build-jcj: orphaned dropdown JS survived upstream" }
Write-Output "  header inherited : ok"

# hero PARKED (v9, JC 7/20): the whole "Mucus-Free Made Simple" hero is gone;
# the webinar banner is now the top of the page. The v8 hero (JC's intro line +
# trimmed lede) is saved verbatim in src\jcj-parts\parked-hero.html with its
# restore recipe; the v4-v6 hero transform steps live in git history
# (438db1b..9b7af9d) if the transform route is ever preferred.
# 2026-09-19: the library hero now CONTAINS the MDHS video block (nested divs),
# so this removal is also what keeps the hub video-free. The lazy .*? still ends
# at the </div> that precedes <section id="library">, because of the lookahead.
RepRx 'hero-remove' '(?s)<div class="hero">.*?</div>\s*(?=<section id="library">)' '' 1
if ($h -match 'youtube\.com/embed/') { throw "build-jcj: a YouTube embed survived the hero removal" }

# ORDER (JC 2026-09-19, dictated): the TD101 sign-up box is THE FIRST and the
# ONLY thing above the fold -> the two free doors (library, recipe book) -> socials.
# ⛔ NO VIDEO ON THE HUB. His words: "the only thing they see when they first
# click on it is ... to sign up for the Transition Diet 101 course ... at the very
# bottom it just says free resource library or free recipe book ... and then my
# socials ... the main thing they see is just that main thing of get access now."
# The interview video that sat first (Ep.2 with Jerome Shaw, kGm-xJvWYlw) is OFF
# the hub. The "What Is the MDHS?" video (Djygxncc58I) now PLAYS on the library
# page (build-library-page.ps1, hero). video.html stays on disk as a parked part.
# ⛔ _cu\site_swap.py (the event-day hub video swap) is RETIRED by this order and
# aborts by design: there is no <section id="video"> on the hub to swap.
# History: v13 (7/24) video first -> CTA -> library -> socials. v14 (8/25) the CTA
# became the TD101 waitlist box. 9/01 the box became the Substack embed.
RepRx 'cta-insert' ([regex]::Escape('<section id="library">')) ((Part 'cta-block.html') + "`n" + '<section id="library">') 1
# 2026-09-01: cta-block now holds the Substack embed, no __SIGNUP__ link left to resolve.
if ($h -match '__SIGNUP__') { throw "build-jcj: __SIGNUP__ token present but the CTA is the Substack embed now" }
if (([regex]::Matches($h, 'substack\.com/embed')).Count -ne 1) { throw "build-jcj: expected exactly 1 Substack embed in cta-block" }
if ($h -match 'calendly\.com') { throw "build-jcj: a calendly link resurfaced in cta-block" }
# JC 2026-09-01: no Contact surface on ANY site. Catch the parked parts (new-mnav, webinar-banner) if they ever get included.
# 2026-09-02: pattern tightened to the parked parts' EXACT strings. The old bare 'Get In Contact'
# false-fired (PS -match is case-insensitive) on legitimate library body copy in the fat/lean topic
# ("...get in contact..."), which ships on the library page and is stripped from this page later anyway.
if ($h -match '#work-with-us|>\s*Contact\s*<|Get In Contact With The Team') { throw "build-jcj: a Contact link resurfaced (JC: no contact surface on any site)" }
RepRx 'library-heading' ([regex]::Escape('<!-- READ-IN-ORDER PATH -->')) ('<div class="sect-head">' + "`n" + '        <p class="kicker k-free">Free &middot; No Email Signup Required</p>' + "`n" + '        <h2>The Free Library</h2>' + "`n" + '      </div>' + "`n" + '      <!-- READ-IN-ORDER PATH -->') 1

# TD101 course parked -> LIVE (2026-08-21). The library upstream now ships 14
# LIVE tdlink anchors (JC overruled the 2026-08-11 "parked" downgrade), so this
# page inherits live anchors, not dead spans. Assert the new reality, do not
# repeat the old one. This inherited body is discarded a few steps down by the
# "library -> pointer" replace, so nothing here reaches the final page, but the
# assert must still match or the build throws.
if ([regex]::Matches($h, '<a class="tdlink[^"]*" href=').Count -ne 14) { throw "build-jcj: expected 14 inherited live tdlinks" }
if ([regex]::Matches($h, '<span class="tdlink">').Count -ne 0) { throw "build-jcj: a dead tdlink span survived upstream" }
Write-Output "  parked course inherited : 14 ok"
RepRx 'course-note-chip' ([regex]::Escape('Transition Diet 101</a> teaches.</span></div>')) ('Transition Diet 101</a> teaches. <span class="soonchip">Coming Soon</span></span></div>') 1
$fr = [regex]::Matches($h, [regex]::Escape('Transition Diet 101</a> course.')).Count
if ($fr -lt 1) { throw "build-jcj: framing-chip found none" }
$h = $h.Replace('Transition Diet 101</a> course.', 'Transition Diet 101</a> course. <span class="soonchip">Coming Soon</span>')
Write-Output "  framing-chip : $fr ok"

# socials after the library (v13, JC 7/24: the CTA block moved up under the video,
# so only socials is inserted here now)
RepRx 'socials-insert' ([regex]::Escape('<dialog id="legalModal">')) ((Part 'socials.html') + "`n" + '<dialog id="legalModal">') 1

# footer (Terms/Medical/Privacy only, no Contact) + mobile pill Library/Socials
RepRx 'footer' '(?s)<footer>.*?</footer>' (Part 'new-footer.html') 1
# THE DOCK BAR is INHERITED from the library master (build-library-page.ps1
# injects it there, and this page is generated from that master, so the layering
# gives it to us for free). ⛔ It carries no Contact/Calendly item (removed
# 2026-08-25, JC): there is no way to book a call from any site in the family.
$dockCount = [regex]::Matches($h, '<nav class="dockbar"').Count
if ($dockCount -ne 1) { throw "build-jcj: expected exactly 1 inherited dock, found $dockCount" }
if ($h -match 'dock-contact|calendly\.com') { throw "build-jcj: a contact/calendly reference resurfaced" }

# full legal docs into the modal
RepRx 'legal-object' '(?m)^const LEGAL=\{.*$' (Part 'legal.js') 1

# JS funnel end-buttons: paid -> socials
RepRx 'endbtn-text' ([regex]::Escape("go.innerHTML='Explore the paid services ")) "go.innerHTML='See my social media " 1
$paidUrl = $LandingUrl + '#paid'
$pc = [regex]::Matches($h, [regex]::Escape($paidUrl)).Count
if ($pc -ne 2) { throw "build-jcj: expected 2 JS paid URLs, found $pc" }
$h = $h.Replace($paidUrl, '#socials')
Write-Output "  js-paid-urls : 2 ok"

# Carrd eats hash navigation -> in-page # links scroll via JS instead (v5)
# ⛔ cta-inline.js DELETED 2026-08-25 (JC): it injected a per-topic Calendly
# "Free 15-Min Call" strip, a second Calendly access point besides cta-block.
$rxScript = New-Object System.Text.RegularExpressions.Regex('(?m)^</script>$')
if (-not $rxScript.IsMatch($h)) { throw "build-jcj: closing script marker not found" }
$jsIns = (Part 'anchor-fix.js').TrimEnd() + "`n</script>"
$h = $rxScript.Replace($h, [System.Text.RegularExpressions.MatchEvaluator]{ param($mm) $jsIns }, 1)
Write-Output "  anchor-fix js merged : ok"

# rebrand CSS merged INTO the main style block (split-jcj expects one block)
$rxStyle = New-Object System.Text.RegularExpressions.Regex('(?m)^</style>$')
if (-not $rxStyle.IsMatch($h)) { throw "build-jcj: closing style marker not found" }
$cssIns = (Part 'jcj-extra.css').TrimEnd() + "`n</style>"
$h = $rxStyle.Replace($h, [System.Text.RegularExpressions.MatchEvaluator]{ param($mm) $cssIns }, 1)
Write-Output "  extra-css merged : ok"

# ---- THE LIBRARY MOVES OUT (JC 2026-08-10) ----
# The hub keeps the "Free, No Email Signup Required / The Free Library" heading
# (his copy, untouched) and now POINTS at the library's own site instead of
# carrying all six topics inline. The hub's job is the video, the human, and
# the routing; the library is its own page in the same design.
$libSectionRx = '(?s)<section id="library">.*?</section>\s*(?=<!-- funnel -->)'
$m = [regex]::Matches($h, $libSectionRx)
if ($m.Count -ne 1) { throw "build-jcj: library section matched $($m.Count), expected 1" }
# 2026-08-11 to 2026-09-19 this was a three-card "Start Here, Free" box (recipes,
# library, course; markup in git history, commit a31c6fa). JC 2026-09-19, dictated:
# "There is just a button that says free resource library and another button that
# says free recipe book. It's just my socials." So: the course card is GONE (the
# Get Access box above IS the course path now, and a second one under it would
# compete with it), the descriptions are gone, and the two buttons carry the exact
# labels he said, in the order he said them. The kicker is his existing copy and
# the one fact that separates these from the sign-up above: they need no email.
$libPointer = @"
<section id="library">
      <div class="sect-head freehead">
        <p class="kicker k-free">Free &middot; No Email Signup Required</p>
      </div>
      <div class="freebtns">
        <a class="btn" href="$LibraryUrl">Free Resource Library</a>
        <a class="btn" href="$RecipesUrl">Free Recipe Book</a>
      </div>
    </section>

"@
$h = [regex]::Replace($h, $libSectionRx, { param($mm) $libPointer })
Write-Output ("  library -> pointer : ok (" + [math]::Round($m[0].Value.Length/1kb) + " KB of inline topics removed)")

# guards
if ([regex]::Matches($h, 'td101landing|td101library').Count -ne 0) { throw "build-jcj: residual dead td101 subdomain refs" }
if ([regex]::Matches($h, 'class="acc cat"').Count -ne 0) { throw "build-jcj: library accordions survived the pointer swap" }
# JC 2026-09-19: sign-up box FIRST, exactly two free buttons with his labels, no
# video anywhere on the hub, and the Substack embed is the hub's one path to the
# course (the 8/21 "at least 2 paths" rule was for the old three-card box; the
# box that replaced it IS the sign-up, at the top, so a second path below would
# compete with it). Each of these was watched failing before it shipped.
if ([regex]::Matches($h, '<a class="btn" href="' + [regex]::Escape($LibraryUrl) + '">Free Resource Library</a>').Count -ne 1) { throw "build-jcj: the Free Resource Library button is missing" }
if ([regex]::Matches($h, '<a class="btn" href="' + [regex]::Escape($RecipesUrl) + '">Free Recipe Book</a>').Count -ne 1) { throw "build-jcj: the Free Recipe Book button is missing" }
if ([regex]::Matches($h, '<div class="startrow">').Count -ne 0) { throw "build-jcj: the old three-card Start Here box resurfaced (JC 2026-09-19: two buttons only)" }
$firstSection = [regex]::Match($h, '(?s)<main class="wrap" id="top">\s*<section id="([^"]+)"')
if (-not $firstSection.Success -or $firstSection.Groups[1].Value -ne 'join-td101') { throw ("build-jcj: the first thing on the hub must be the Get Access box (JC 2026-09-19), found '" + $firstSection.Groups[1].Value + "'") }
if ([regex]::Matches($h, '<section id="video">|youtube\.com/embed/').Count -ne 0) { throw "build-jcj: a video reached the hub (JC 2026-09-19: no video on the homepage; the MDHS video plays on the library page)" }
if (([regex]::Matches($h, 'substack\.com/embed')).Count -ne 1) { throw "build-jcj: the Substack embed is the hub's one path to the course and must appear exactly once" }
Write-Output "  hub: sign-up first, two free doors, no video : ok"
$dockCount = [regex]::Matches($h, '<nav class="dockbar"').Count
if ($dockCount -ne 1) { throw "build-jcj: expected exactly 1 dock in the output, found $dockCount" }
if ([regex]::Matches($h, '(?s)<nav class="mnav"').Count -ne 0) { throw "build-jcj: the old mobile pill resurfaced" }
if ([regex]::Matches($h, 'My Journey').Count -ne 0)   { throw "build-jcj: My Journey resurfaced" }

[IO.File]::WriteAllText("$masters\jcj-page.html", $h, $utf8)
Write-Output ("jcj master written: " + [math]::Round((Get-Item "$masters\jcj-page.html").Length / 1kb) + " KB")
