# Builds the JC'S JOURNALS page (jcsjournals.com): the library page rebranded
# per JC's 7/19 direction — JC's Journals wordmark + social icons in the header,
# brand-colored social cards section, free course/paid tiers PARKED as "coming
# soon" (TD101 links de-linked, not deleted), My Journey removed, full legal
# docs (Terms 2/25 + Medical/Privacy 3/31) in the footer modal, no Contact.
#
# Input : site-masters\mdhs-library-page.html  (generated by build-library-page.ps1 — run that first)
# Parts : repo\src\jcj-parts\*                 (header, socials, footer, mnav, legal docs, extra CSS)
# Output: site-masters\jcj-page.html           (full page master; split-jcj.ps1 makes the CDN files)
#
# Every replacement is verified (exact expected match count) — a drifted master
# fails the build loudly instead of shipping a half-transformed page.
$ErrorActionPreference = 'Stop'
$repo    = "C:\Users\taino\jcsjournals-site"
$masters = "D:\00. MUCUS-FREE LIFE\01. Operations\02. Working Procedures\Claude SOPs\00. JC Brand\JC Website\site-masters"
$parts   = "$repo\src\jcj-parts"
$utf8    = New-Object System.Text.UTF8Encoding($false)

$h = [IO.File]::ReadAllText("$masters\mdhs-library-page.html", [Text.Encoding]::UTF8)
function Part([string]$name) { [IO.File]::ReadAllText("$parts\$name", [Text.Encoding]::UTF8) }

function RepRx([string]$label, [string]$pattern, [string]$replacement, [int]$expect) {
  $m = [regex]::Matches($script:h, $pattern)
  if ($m.Count -ne $expect) { throw "build-jcj: $label matched $($m.Count), expected $expect" }
  $script:h = [regex]::Replace($script:h, $pattern, { param($mm) $replacement })
  Write-Output "  $label : $expect ok"
}

# title ([char]0xB7 = the middle dot; this file is read as ANSI by PS 5.1)
$oldTitle = '<title>Free Education ' + [char]0xB7 + ' The Mucusless Diet Healing System</title>'
RepRx 'title' ([regex]::Escape($oldTitle)) '<title>JC&rsquo;s Journals &middot; Mucus-Free Made Simple</title>' 1

# header -> wordmark + social icons; kill the orphaned dropdown JS
RepRx 'header' '(?s)<header class="site-header">.*?</header>' (Part 'new-header.html') 1
RepRx 'dropdown-js' "(?s)var freeBtn=document\.getElementById\('freeBtn'\).*?(?=document\.querySelectorAll\('\.more-btn'\))" '' 1

# hero (v6): eyebrow deleted entirely — the "Free Library" label now lives
# down on the library section instead; JC's personal line added under the H1
RepRx 'eyebrow-remove' ([regex]::Escape('<p class="eyebrow">The Library &middot; Free &middot; No Email Signup Required</p>')) '' 1
RepRx 'intro-line' ([regex]::Escape('<h1>Mucus-Free<br>Made Simple</h1>')) ('<h1>Mucus-Free<br>Made Simple</h1>' + "`n" + '    <p class="lede intro-line">Explore the 100+ year old knowledge that changed my life.</p>') 1

# hero trims (v4/v5, JC 7/19-20): lede ends at "...revised edition of the MDHS.";
# the pick-a-topic line and the click-out video pill are both deleted. v5: the
# three jump buttons are GONE too (Carrd hijacked their # links, so they did
# nothing) — the video + library now sit directly under the hero text instead.
RepRx 'lede-trim' ([regex]::Escape(': his annotations make everything easier to understand.</p>')) '.</p>' 1
RepRx 'pick-a-topic-remove' ([regex]::Escape('<p class="lede">Pick a topic below; each one opens right where it is.</p>')) '' 1
RepRx 'vidrow-remove' '(?s)<a class="vidrow".*?</a>' '' 1

# ORDER (v8): hero -> webinar banner -> video -> library -> socials
# v6 dividers DELETED in v7 (JC 7/20 — Carrd's own hr styling threw them off-center)
# v8 (JC 7/20): the "Overcoming Fatigue & Bloating" webinar promo card sits
# between the hero and the video; drop it from this insert after the 7/23 event.
RepRx 'webinar+video-insert' ([regex]::Escape('<section id="library">')) ((Part 'webinar-banner.html') + "`n" + (Part 'video.html') + "`n" + '<section id="library">') 1
RepRx 'library-heading' ([regex]::Escape('<!-- READ-IN-ORDER PATH -->')) ('<div class="sect-head">' + "`n" + '        <p class="kicker k-free">Free &middot; No Email Signup Required</p>' + "`n" + '        <h2>The Free Library</h2>' + "`n" + '      </div>' + "`n" + '      <!-- READ-IN-ORDER PATH -->') 1

# TD101 course parked: green button -> ghost+soon, links -> plain gold spans, soon chips
RepRx 'green-course-btn' ([regex]::Escape('<a class="btn green" class="tdlink" href="https://td101landing.carrd.co/#free">What Is Transition Diet 101?</a>')) '<span class="btn ghost">What Is Transition Diet 101? <span class="chip">soon</span></span>' 1
$m = [regex]::Matches($h, '<a class="tdlink" href="[^"]*">(.*?)</a>')
if ($m.Count -ne 14) { throw "build-jcj: tdlink matched $($m.Count), expected 14" }
$h = [regex]::Replace($h, '<a class="tdlink" href="[^"]*">(.*?)</a>', '<span class="tdlink">$1</span>')
Write-Output "  tdlink->span : 14 ok"
RepRx 'course-note-chip' ([regex]::Escape('Transition Diet 101</span> teaches.</span></div>')) ('Transition Diet 101</span> teaches. <span class="soonchip">Coming Soon</span></span></div>') 1
$fr = [regex]::Matches($h, [regex]::Escape('Transition Diet 101</span> course.')).Count
if ($fr -lt 1) { throw "build-jcj: framing-chip found none" }
$h = $h.Replace('Transition Diet 101</span> course.', 'Transition Diet 101</span> course. <span class="soonchip">Coming Soon</span>')
Write-Output "  framing-chip : $fr ok"

# the big CTA block, then socials, after the library (v7)
RepRx 'cta+socials-insert' ([regex]::Escape('<dialog id="legalModal">')) ((Part 'cta-block.html') + "`n" + (Part 'socials.html') + "`n" + '<dialog id="legalModal">') 1

# footer (Terms/Medical/Privacy only, no Contact) + mobile pill Library/Socials
RepRx 'footer' '(?s)<footer>.*?</footer>' (Part 'new-footer.html') 1
RepRx 'mnav' '(?s)<nav class="mnav"[^>]*>.*?</nav>' (Part 'new-mnav.html') 1

# full legal docs into the modal
RepRx 'legal-object' '(?m)^const LEGAL=\{.*$' (Part 'legal.js') 1

# JS funnel end-buttons: paid -> socials
RepRx 'endbtn-text' ([regex]::Escape("go.innerHTML='Explore the paid services ")) "go.innerHTML='See my social media " 1
$pc = [regex]::Matches($h, [regex]::Escape('https://td101landing.carrd.co/#paid')).Count
if ($pc -ne 2) { throw "build-jcj: expected 2 JS paid URLs, found $pc" }
$h = $h.Replace('https://td101landing.carrd.co/#paid', '#socials')
Write-Output "  js-paid-urls : 2 ok"

# Carrd eats hash navigation -> in-page # links scroll via JS instead (v5)
$rxScript = New-Object System.Text.RegularExpressions.Regex('(?m)^</script>$')
if (-not $rxScript.IsMatch($h)) { throw "build-jcj: closing script marker not found" }
$jsIns = (Part 'anchor-fix.js').TrimEnd() + "`n" + (Part 'cta-inline.js').TrimEnd() + "`n</script>"
$h = $rxScript.Replace($h, [System.Text.RegularExpressions.MatchEvaluator]{ param($mm) $jsIns }, 1)
Write-Output "  anchor-fix js merged : ok"

# rebrand CSS merged INTO the main style block (split-jcj expects one block)
$rxStyle = New-Object System.Text.RegularExpressions.Regex('(?m)^</style>$')
if (-not $rxStyle.IsMatch($h)) { throw "build-jcj: closing style marker not found" }
$cssIns = (Part 'jcj-extra.css').TrimEnd() + "`n</style>"
$h = $rxStyle.Replace($h, [System.Text.RegularExpressions.MatchEvaluator]{ param($mm) $cssIns }, 1)
Write-Output "  extra-css merged : ok"

# guards
if ([regex]::Matches($h, 'td101landing').Count -ne 0) { throw "build-jcj: residual td101landing refs" }
if ([regex]::Matches($h, 'My Journey').Count -ne 0)   { throw "build-jcj: My Journey resurfaced" }

[IO.File]::WriteAllText("$masters\jcj-page.html", $h, $utf8)
Write-Output ("jcj master written: " + [math]::Round((Get-Item "$masters\jcj-page.html").Length / 1kb) + " KB")
